collections:
  - name: cloud.terraform
    version: 3.0.0
  - name: nycmesh.common
    source: git+https://github.com/nycmeshnet/nycmesh-ansible.git
    type: git
    version: main
  - name: ansible.utils
    version: 5.1.2
