## Wireguard config
- name: Stat of wireguard config wg{{ item.NAME }} - before
  ansible.builtin.stat:
    path : "/etc/wireguard/wg{{ item.NAME }}"
  register: config_before

- name: Copy wireguard config wg{{ item.NAME }}
  ansible.builtin.template:
    src: ./templates/wg.conf.j2
    dest: "/etc/wireguard/wg{{ item.NAME }}"
    owner: root
    group: root
    mode: "0600"

- name: Stat of wireguard config wg{{ item.NAME }} - after
  ansible.builtin.stat:
    path : "/etc/wireguard/wg{{ item.NAME }}"
  register: config_after

## Interface definition
- name: Stat of interface definition wg{{ item.NAME }} - before
  ansible.builtin.stat:
    path : "/etc/network/interfaces.d/wg{{ item.NAME }}"
  register: interface_before

- name: Copy interface definition wg{{ item.NAME }}
  ansible.builtin.template:
    src: ./templates/wg_interface.j2
    dest: "/etc/network/interfaces.d/wg{{ item.NAME }}"
    owner: root
    group: root
    mode: "0600"

- name: Stat of interface definition wg{{ item.NAME }} - after
  ansible.builtin.stat:
    path : "/etc/network/interfaces.d/wg{{ item.NAME }}"
  register: interface_after

## Bounce
- name: Bounce interface if it anything changed
  ansible.builtin.command:
    cmd: "bash -c 'service networking reload;ifdown --force wg{{ item.NAME }};ifup wg{{ item.NAME }}'"
  when: (interface_before.stat.checksum is not defined or config_before.stat.checksum is not defined) or (interface_before.stat.checksum != interface_after.stat.checksum) or (config_before.stat.checksum != config_after.stat.checksum)
